### ISSUE TITLE
关于JQ

### ISSUE THREAD

**Issue by JoeBBChen** [topview-frontend/learnJavaScriptProperly#16]
![image](https://cloud.githubusercontent.com/assets/12586787/8889654/491cee80-3316-11e5-8789-9c357bc175a6.png)

JS用这个来判断是否选中，那JQ怎么写？我卡了很久，求回答。。。

**Comment by SelinaYu** [comment]
用 `var value =$("input[type='radio']:checked").val();`
然后判断其值是否为undefined来判断是被选中
