### ISSUE TITLE
修改字体大小不起作用

### ISSUE THREAD

**Issue by JoeBBChen** [topview-frontend/learnJavaScriptProperly#2]
在codecademy那里敲样例时敲字体大小为10px，但是它报错说字体大小为12px，后来想想之前也遇到类似的问题，就百度一下怎么办，真的是浏览器问题，浏览器默认最小字体是12px，所以小于12px的的样式都忽略。。。之前遇到类似的问题就是不同的字体设置同样的大小，结果字体显示大小是不一样的，这好像也是浏览器自带样式的问题，所以有时候要改变浏览器的默认样式。至于什么时候浏览器默认样式会影响我们自己的样式，我还不是很清楚。
![qq 20150712051227](https://cloud.githubusercontent.com/assets/6823863/8636494/aac20e06-2897-11e5-8d88-1498a067d1cc.png)

**Comment by lyyourc** [comment]
解决：更换浏览器
