### ISSUE TITLE
About Quiz

### ISSUE THREAD

**Issue by jasonliao** [topview-frontend/learnJavaScriptProperly#29]
只是简单的看看代码，里面的问题可能出现在你们几个人中的一个或者几个
## Project Structure

```
.
├─ 1.jpg
├─ 2.jpg
├─ 3.jpg
├─ A Dynamic Quiz.html
├─ A Dynamic Quiz.css
├─ A Dynamic Quiz.js
```

**不要再在一个文件夹里放所有类型的文件**

不同的项目类型可能分的文件夹会不一样，希望可以在学习别人代码的时候，也可以学习别人是怎么给代码分类分层次
## Style Guide

**在遵循代码规范的情况下，请保持代码风格的一致性。**
- HTML
  - HTML 中标签属性等号两边不需要空格了
  - 尽量不要在标签里添加样式
  - 标签类与 id 的命名请符合语义。`id="2"` 这样的尽量不要出现
- CSS

``` css
*{
  margin:0px;
  padding:0px;
  /* ... */
}
#screen {
  content: '';
  background: url('../image/bg.png');
  /* ... */
}
```

**请保持代码风格的一致**
- JavaScript

我在同一个 `.js` 文件里看到一个判断语句的N种写法

``` javascript
// 1
if(){
}
else {
}

// 2
if() {
}
else{
}

// 3
if () {
} else {
}

// 自行自由组合
```

**请保持代码风格的一致**
## Code Optimization
1. 学会简单地封装一些函数
   
   如果你不喜欢看到满屏的 `document.getElementById()`，你可以简单的这样
   
   ``` javascript
   function $ (id) {
     return document.getElementById(id);
   }
   
   var bgPage = $('bgPage');
   ```
2. 不要把所有的东西都放到一个函数里或者一个文件里
   
   可以把不同的操作封在不同的函数里，放在不同的文件里，模块化一下。
   
   远成大大也下指令了，MVC 啊
3. 注意细节
   
   我看到这样的
   
   ``` javascript
   var record = new Array(10);
   for(var i = 0; i < 10; i++) {
     record[i] = 'false';
   }
   ```
   
   首先，不说这样写好不好。我想指出的是，在后面的代码中，对这个 `record` 数组里赋值的都是 `true` or `false`。而这位同学一下子喜欢用 `==` 来判断，一下子喜欢用 `===` 来判断。
## User Experiences

选择答案的时候，一定要点击小点点这个就不好了吧，用一个 `label` `for` 一下，还是很不错的。答题的时候，返回上一题没有记住我的答案差评。
## Use README

所有人的 README 就只有项目名和描述一定是新建仓库的时候顺便勾上的啦，要好好利用 README，因为别人进来你的仓库看到的就是这个，你可以在上面写写你这个 Quiz 有什么与众不同的地方呀，有什么 new features 呀，有什么 Bug 呀，可以来个 screenshot 呀，有弄了 GitHub Page 的也可以放上网址呀等等等等。
## Last

已经很厉害了，好好跟远成大大混，我也是跟他混的，明天他生日，就每人给他买点吃的就行。

**Comment by skykobe** [comment]
_受教了，自己的确出现了很多问题，继续改正_
（顺便评论了）

**Comment by byronlun** [comment]
谢谢杰斌大大，发现了一些我的问题，继续修改，杰斌大大快回来，远成大大需要你，我们也在召唤你
