### ISSUE TITLE
关于使用arguments的一些疑问

### ISSUE THREAD

**Issue by skykobe** [topview-frontend/learnJavaScriptProperly#3]
**为什么用字符串的时候没反应，我用数字，或者单个字符的时候是没问题的**

``` html
<!DOCTYPE html>
   <html>
       <head>
            <title>TEST</title>
            <script>
            function test() {
                 var num=arguments.lenght;
                 var string="";
                 for(var i=0;i<num;i++)
                 {
                         string+=arguments[i];
                 }
                alert(string);
            }
            </script>
           <script>
                 window.onload=test(”Hello“,”World!“);
           </script>
       </head>
      <body>
      </body>
   </html>
```

**Comment by lyyourc** [comment]
**代码不要截图!!!**

### script标签
- 不需要写`type`属性，如果忽略的话，默认为javascript.
- 在没有`src`属性下，不要写`defer`属性，而且`defer`不兼容所有浏览器。
- 详情看[doc](http://devdocs.io/html/element/script)

**Comment by ccDeng** [comment]
TAT 心好痛 明明提交了居然没有又要打一次
1.运算符两边加空格
2.JS尽量用单引号，HTML跟css尽量用双引号，因为很有可能里面要有双引号""，详细请见楼上的doc链接，谢谢 修正onload = "test('hello','world')"就可以正常运行了

**Comment by ccDeng** [comment]
<!doctype html>
    <html lang="en">
    <head>
	    <meta charset="UTF-8">
	    <title>Demo</title>
	    <script>
		    function test() {
			    var num = arguments.length;
			    var string = '';
			    for(var i = 0;i < num;i++) {
				    alert(arguments[i]);
				    string += arguments[i];
			    }
			    alert(string);
		    }
		    test('hello','world');
	    </script>
    </head>

<body>
</body>
</html>

**Comment by ccDeng** [comment]
<!doctype html>
    <html lang="en">
    <head>
	    <meta charset="UTF-8">
	    <title>Demo</title>
	    <script>
	 	    function test() {
			    var num = arguments.length;
			    var string = '';
			    for(var i = 0;i < num;i++) {
				    alert(arguments[i]);
				    string += arguments[i];
			    }
			    alert(string);
		    }
		    test('hello','world');
	    </script>
    </head>

    <body>
    </body>
    </html>

**Comment by ccDeng** [comment]
```html
    <!doctype html>
    <html lang="en">
    <head>
	    <meta charset="UTF-8">
	    <title>Demo</title>
	    <script>
	 	    function test() {
			    var num = arguments.length;
			    var string = '';
			    for(var i = 0;i < num;i++) {
				    alert(arguments[i]);
				    string += arguments[i];
			    }
			    alert(string);
		    }
		    test('hello','world');
	    </script>
    </head>

    <body>
    </body>
    </html>
```

**Comment by ccDeng** [comment]
1.运算符两边加空格
2.JS尽量用单引号，HTML跟css尽量用双引号，因为很有可能里面要有双引号""，详细请见楼上的doc链接，谢谢 修正onload = "test('hello','world')"就可以正常运行了
3.代码如下

``` html
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Demo</title>
        <script>
            function test() {
                var num = arguments.length;
                var string = '';
                for(var i = 0;i < num;i++) {
                    alert(arguments[i]);
                    string += arguments[i];
                }
                alert(string);
            }
            addEventListener(onload,test('hello','world'));
        </script>
    </head>

    <body>
    </body>
    </html>
```
