### ISSUE TITLE
7/13进度

### ISSUE THREAD

**Issue by byronlun** [topview-frontend/learnJavaScriptProperly#4]
### 今日收获
1. 复习了HTML和CSS
2. 终于入门了JavaScript
3. 学习了JavaScript的一些基本语法，数据类型之类
### 学习进度
1. _JavaScript高级程序_设计看完第四章
2. codecademy的JavaScript课程做到Control flow

**Comment by skykobe** [comment]
#### 今日战果
1. 开始刷**HTML和CSS的题目**
2. _Javascript_学习到了第五章，明天继续努力。
3. 今天最后还学习了Markdown语法。

### 今日进度
1. JavaScript高级程序设计
2. html/css,JavaScript刷了一部分

**Comment by jasonliao** [comment]
完成了任务模块的所有交接 等测试  :persevere: 

# I miss you all!

**Comment by ccDeng** [comment]
### 今日收获

1.学习了一些Markdown语法
2.看了JS基础

### 学习进度

1.完成JS高级程序设计第四章
2.完成JS课程第八部分

**Comment by SelinaYu** [comment]
# 今日收获
1. 完成HTML和CSS部分
2. 学习javascript
3. 看了下Git教程

# 学习进度
1. 还在看高级程序设计第四章
2. codecademy:'WHILE' LOOPS IN JAVASCRIPT
