### ISSUE TITLE
7/14进度

### ISSUE THREAD

**Issue by byronlun** [topview-frontend/learnJavaScriptProperly#5]
### 学习进度
1. 学了JavaScript的第5章，还有第6章的了解对象。
2.  codecademy中JavaScript题目做到object1。
### 学习成果
1. 刷题过程学会一些细节，易错点。

**Comment by ccDeng** [comment]
#### 学习进度
1. 看到函数表达式的闭包
2. 学了引用类型

**Comment by ccDeng** [comment]
#### 学习进度
1. 看到函数表达式的闭包
2. 学了引用类型

#### 学习成果
1. 了解函数对象，做题过程中也发现了很多小知识

**Comment by skykobe** [comment]
## 今日收获
- 复习了一下正则表达式
- 百度了一下栈，结合看了一下Array类型的一些函数功能
- 刷题过程中又小小的了解了一下CSS3的新选择器 

## 学习进度
- html的题**才**刷到95%
- 书本的话才接近看完第五章

**Comment by JoeBBChen** [comment]
学习进度
1:看到第五章。2:codeacademy在object那里。
收获
最大的收获就是锻炼了找bug的能力和耐心。。。

**Comment by SelinaYu** [comment]
今日收获
1.高级程序设计看到第五章
2.codecademy在做到object
